// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto
#ifndef GRPC_service_2eproto__INCLUDED
#define GRPC_service_2eproto__INCLUDED

#include "service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class Profile final {
 public:
  static constexpr char const* service_full_name() {
    return "Profile";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status EnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::EnableProfilingReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::EnableProfilingReply>> AsyncEnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::EnableProfilingReply>>(AsyncEnableProfilingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::EnableProfilingReply>> PrepareAsyncEnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::EnableProfilingReply>>(PrepareAsyncEnableProfilingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void EnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest* request, ::EnableProfilingReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void EnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest* request, ::EnableProfilingReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::EnableProfilingReply>* AsyncEnableProfilingRaw(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::EnableProfilingReply>* PrepareAsyncEnableProfilingRaw(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status EnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::EnableProfilingReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::EnableProfilingReply>> AsyncEnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::EnableProfilingReply>>(AsyncEnableProfilingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::EnableProfilingReply>> PrepareAsyncEnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::EnableProfilingReply>>(PrepareAsyncEnableProfilingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void EnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest* request, ::EnableProfilingReply* response, std::function<void(::grpc::Status)>) override;
      void EnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest* request, ::EnableProfilingReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::EnableProfilingReply>* AsyncEnableProfilingRaw(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::EnableProfilingReply>* PrepareAsyncEnableProfilingRaw(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_EnableProfiling_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status EnableProfiling(::grpc::ServerContext* context, const ::EnableProfilingRequest* request, ::EnableProfilingReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_EnableProfiling : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_EnableProfiling() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_EnableProfiling() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnableProfiling(::grpc::ServerContext* /*context*/, const ::EnableProfilingRequest* /*request*/, ::EnableProfilingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnableProfiling(::grpc::ServerContext* context, ::EnableProfilingRequest* request, ::grpc::ServerAsyncResponseWriter< ::EnableProfilingReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_EnableProfiling<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_EnableProfiling : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_EnableProfiling() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::EnableProfilingRequest, ::EnableProfilingReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::EnableProfilingRequest* request, ::EnableProfilingReply* response) { return this->EnableProfiling(context, request, response); }));}
    void SetMessageAllocatorFor_EnableProfiling(
        ::grpc::MessageAllocator< ::EnableProfilingRequest, ::EnableProfilingReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::EnableProfilingRequest, ::EnableProfilingReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_EnableProfiling() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnableProfiling(::grpc::ServerContext* /*context*/, const ::EnableProfilingRequest* /*request*/, ::EnableProfilingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EnableProfiling(
      ::grpc::CallbackServerContext* /*context*/, const ::EnableProfilingRequest* /*request*/, ::EnableProfilingReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_EnableProfiling<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_EnableProfiling : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_EnableProfiling() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_EnableProfiling() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnableProfiling(::grpc::ServerContext* /*context*/, const ::EnableProfilingRequest* /*request*/, ::EnableProfilingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_EnableProfiling : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_EnableProfiling() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_EnableProfiling() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnableProfiling(::grpc::ServerContext* /*context*/, const ::EnableProfilingRequest* /*request*/, ::EnableProfilingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestEnableProfiling(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_EnableProfiling : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_EnableProfiling() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->EnableProfiling(context, request, response); }));
    }
    ~WithRawCallbackMethod_EnableProfiling() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status EnableProfiling(::grpc::ServerContext* /*context*/, const ::EnableProfilingRequest* /*request*/, ::EnableProfilingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* EnableProfiling(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_EnableProfiling : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_EnableProfiling() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::EnableProfilingRequest, ::EnableProfilingReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::EnableProfilingRequest, ::EnableProfilingReply>* streamer) {
                       return this->StreamedEnableProfiling(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_EnableProfiling() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status EnableProfiling(::grpc::ServerContext* /*context*/, const ::EnableProfilingRequest* /*request*/, ::EnableProfilingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedEnableProfiling(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::EnableProfilingRequest,::EnableProfilingReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_EnableProfiling<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_EnableProfiling<Service > StreamedService;
};


#endif  // GRPC_service_2eproto__INCLUDED
