// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Profile_method_names[] = {
  "/Profile/EnableProfiling",
};

std::unique_ptr< Profile::Stub> Profile::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Profile::Stub> stub(new Profile::Stub(channel, options));
  return stub;
}

Profile::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_EnableProfiling_(Profile_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Profile::Stub::EnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::EnableProfilingReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::EnableProfilingRequest, ::EnableProfilingReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EnableProfiling_, context, request, response);
}

void Profile::Stub::async::EnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest* request, ::EnableProfilingReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::EnableProfilingRequest, ::EnableProfilingReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnableProfiling_, context, request, response, std::move(f));
}

void Profile::Stub::async::EnableProfiling(::grpc::ClientContext* context, const ::EnableProfilingRequest* request, ::EnableProfilingReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EnableProfiling_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::EnableProfilingReply>* Profile::Stub::PrepareAsyncEnableProfilingRaw(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::EnableProfilingReply, ::EnableProfilingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EnableProfiling_, context, request);
}

::grpc::ClientAsyncResponseReader< ::EnableProfilingReply>* Profile::Stub::AsyncEnableProfilingRaw(::grpc::ClientContext* context, const ::EnableProfilingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEnableProfilingRaw(context, request, cq);
  result->StartCall();
  return result;
}

Profile::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Profile_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Profile::Service, ::EnableProfilingRequest, ::EnableProfilingReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Profile::Service* service,
             ::grpc::ServerContext* ctx,
             const ::EnableProfilingRequest* req,
             ::EnableProfilingReply* resp) {
               return service->EnableProfiling(ctx, req, resp);
             }, this)));
}

Profile::Service::~Service() {
}

::grpc::Status Profile::Service::EnableProfiling(::grpc::ServerContext* context, const ::EnableProfilingRequest* request, ::EnableProfilingReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


